name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: construct
      id: construct
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: construct
        setup-command: make
        command: "./inh 111 012  3.0 pupha 222 120  3.1 ryan 333 221  2.3 Mix"
        input: ''
        expected-output: |-
          adding 111
          MU person constructor 12
          MU student constructor  3
          adding 222
          MU person constructor 120
          MU student constructor  3.1
          adding 333
          MU person constructor 221
          MU student constructor  2.3
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: show all
      id: show-all
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: show all
        setup-command: make
        command: "./inh 111 012  3.0 pupha 222 120  3.1 ryan 444 221  2.3 Mix"
        input: ''
        expected-output: |-
          Node data:444
          Node data:222
          Node data:111
        comparison-method: contains
        timeout: 10
        max-score: 15
    - name: destruct
      id: destruct
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: destruct
        setup-command: make
        command: "./inh 111 012  3.0 pupha 222 120  3.1 ryan 444 221  2.3 Mix"
        input: ''
        expected-output: |-
          Node 444 is being deleted
          Node 222 is being deleted
          Node 111 is being deleted
        comparison-method: contains
        timeout: 10
        max-score: 29
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CONSTRUCT_RESULTS: "${{steps.construct.outputs.result}}"
        SHOW-ALL_RESULTS: "${{steps.show-all.outputs.result}}"
        DESTRUCT_RESULTS: "${{steps.destruct.outputs.result}}"
      with:
        runners: construct,show-all,destruct
